In [2]:
import pandas as pd

# Cambia la ruta a tu archivo
ruta = "C:/Users/EL ADMIN/Documents/SI807_Cloud_BI_2025/grupo01_interbank/MiniProyecto/data/raw/netflix_titles.csv"

# Lee el CSV (detecta encabezados por defecto)
df = pd.read_csv(ruta, encoding="utf-8", sep=",")   # usa sep=";" si tu CSV est√° separado por punto y coma
print(df.head())  # primeras 5 filas

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df = pd.read_csv("C:/Users/EL ADMIN/Documents/SI807_Cloud_BI_2025/grupo01_interbank/MiniProyecto/data/raw/netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [5]:

print("# 1) Vista general: filas/columnas, nulos, tipos inferidos")
print(df.shape)
print(df.info())
print(df.head(3))

print("# 2) Porcentaje de nulos por columna")
null_pct = df.isna().mean().sort_values(ascending=False)
print(null_pct.head(10))

print("# 3) Duplicados de filas completas")
print("Filas duplicadas:", df.duplicated().sum())

print("# 4) Cardinalidad y muestra de categor√≠as (para columnas tipo 'object')")
cat_cols = df.select_dtypes(include="object").columns
for c in cat_cols:
    print(f"\n[{c}] √∫nicos:", df[c].nunique())
    print(df[c].dropna().astype(str).str.strip().str.lower().value_counts().head(5))

print("# 5) ¬øN√∫meros guardados como texto?")
num_like = []
for c in df.columns:
    # prueba convertir a num√©rico
    coerced = pd.to_numeric(df[c].astype(str).str.replace(",", ".", regex=False), errors="coerce")
    ratio_numeric = coerced.notna().mean()
    if ratio_numeric > 0.7 and str(df[c].dtype) == "object":
        num_like.append((c, ratio_numeric))
print("Columnas que parecen num√©ricas pero son texto:", num_like)

print("# 6) Fechas como texto (intenta parseo r√°pido)")
date_candidates = [c for c in df.columns if "fecha" in c.lower() or "date" in c.lower()]
for c in date_candidates:
    parsed = pd.to_datetime(df[c], errors="coerce", dayfirst=True)
    print(f"{c}: % parseable ->", parsed.notna().mean())

print("# 7) Outliers con IQR (para num√©ricas reales)")
num_cols = df.select_dtypes(include=["number"]).columns
for c in num_cols:
    q1, q3 = df[c].quantile([0.25, 0.75])
    iqr = q3 - q1
    if iqr > 0:
        outliers = ((df[c] < (q1 - 1.5*iqr)) | (df[c] > (q3 + 1.5*iqr))).mean()
        print(f"{c}: % outliers (IQR) -> {outliers:.2%}")

print("# 8) Espacios y may√∫sculas inconsistentes (sample)")
for c in cat_cols[:5]:
    sample_rare = (
        df[c].dropna().astype(str)
        .value_counts()
        .tail(3)
    )
    print(f"\nValores raros en {c} (muestra):\n", sample_rare)

# 1) Vista general: filas/columnas, nulos, tipos inferidos
(8807, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB
None
  show_id     type                 title         director  \
0      s1    Movie  Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show         Blood & Water              NaN
2      s3  TV Show             Ganglands  Julien Leclercq

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
# 2) Porcentaje de nulos por columna
director        0.299080
country         0.094357
cast            0.093675
date_added      0.001135
rating          0.000454
duration        0.000341
show_id         0.000000
type            0.000000
title           0.000000
release_year    0.000000
dtype: float64
# 3) Duplicados de filas completas
Filas duplicadas: 0
# 4) Cardinalidad y muestra de categor√≠as (para columnas tipo 'object')

[show_id] √∫nicos: 8807
show_id
s1       1
s5875    1
s5869    1
s5870    1
s5871    1
Name: count, dtype: int64

[type] √∫nicos: 2
type
movie      6131
tv show    2676
Name: count, dtype: int64

[title] √∫nicos: 8807
title
consequences                2
sin senos s√≠ hay para√≠so    2
death note                  2
esperando la carroza        2
love in a puff              2
Name: count, dtype: int64

[director] √∫nicos: 4528
director
rajiv chilaka             19
ra√∫l campos, jan suter    18
suhas kadav               16
marcus raboy              16
jay karas                 14
Name: count, dtype: int64

[cast] √∫nicos: 7692
cast
david attenborough                                                                         19
vatsal dubey, julie tejwani, rupa bhimani, jigna bhardwaj, rajesh kava, mousam, swapnil    14
samuel west                                                                                10
jeff dunham                                                                                 7
david spade, london hughes, fortune feimster                                                6
Name: count, dtype: int64

[country] √∫nicos: 748
country
united states     2818
india              972
united kingdom     419
japan              245
south korea        199
Name: count, dtype: int64

[date_added] √∫nicos: 1767
date_added
january 1, 2020      110
november 1, 2019      91
march 1, 2018         75
december 31, 2019     74
october 1, 2018       71
Name: count, dtype: int64

[rating] √∫nicos: 17
rating
tv-ma    3207
tv-14    2160
tv-pg     863
r         799
pg-13     490
Name: count, dtype: int64

[duration] √∫nicos: 220
duration
1 season     1793
2 seasons     425
3 seasons     199
90 min        152
94 min        146
Name: count, dtype: int64

[listed_in] √∫nicos: 514
listed_in
dramas, international movies                        362
documentaries                                       359
stand-up comedy                                     334
comedies, dramas, international movies              274
dramas, independent movies, international movies    252
Name: count, dtype: int64

[description] √∫nicos: 8775
description
paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think.    4
challenged to compose 100 songs before he can marry the girl he loves, a tortured but passionate singer-songwriter embarks on a poignant musical journey.    3
a surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 3
multiple women report their husbands as missing but when it appears they are looking for the same man, a police officer traces their cryptic connection.     3
secrets bubble to the surface after a sensual encounter and an unforeseen crime entangle two friends and a woman caught between them.                        2
Name: count, dtype: int64
# 5) ¬øN√∫meros guardados como texto?
Columnas que parecen num√©ricas pero son texto: []
# 6) Fechas como texto (intenta parseo r√°pido)
date_added: % parseable -> 0.9888724877938004
# 7) Outliers con IQR (para num√©ricas reales)
release_year: % outliers (IQR) -> 8.16%
# 8) Espacios y may√∫sculas inconsistentes (sample)

Valores raros en show_id (muestra):
 show_id
s2929    1
s2928    1
s8807    1
Name: count, dtype: int64

Valores raros en type (muestra):
 type
Movie      6131
TV Show    2676
Name: count, dtype: int64

Valores raros en title (muestra):
 title
Good Time                                1
Captain Underpants Epic Choice-o-Rama    1
Zubaan                                   1
Name: count, dtype: int64

Valores raros en director (muestra):
 director
Eric Bross        1
Will Eisenberg    1
Mozez Singh       1
Name: count, dtype: int64

Valores raros en cast (muestra):
 cast
Takeru Sato, Kasumi Arimura, Haru, Kentaro Sakaguchi, Takayuki Yamada, Kendo Kobayashi, Ken Yasuda, Arata Furuta, Suzuki Matsuo, Koichi Yamadera, Arata Iura, Chikako Kaku, Kotaro Yoshida    1
Toyin Abraham, Sambasa Nzeribe, Chioma Chukwuka Akpotha, Chioma Omeruah, Chiwetalu Agu, Dele Odule, Femi Adebayo, Bayray McNwizu, Biodun Stephen                                              1
Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy                                                         1
Name: count, dtype: int64

In [6]:

print("# 1) Normalizar strings b√°sicos")
text_cols = ["type","title","director","cast","country","rating","duration","listed_in","description","date_added"]
for c in text_cols:
    df[c] = df[c].astype(str).str.strip()

print("# Opcional: una copia 'normalizada' para detectar duplicados l√≥gicos")
df_norm = df.copy()
for c in ["type","title","country"]:
    df_norm[c] = (df_norm[c]
                  .str.normalize("NFKD")  # quita acentos si quieres
                  .str.encode("ascii","ignore").str.decode("utf-8")
                  .str.strip().str.lower())

print("# 2) Detectar t√≠tulos duplicados 'l√≥gicos'")
dupes_titulo = df_norm.duplicated(subset=["title"], keep=False)
duplicados_logicos = df.loc[dupes_titulo, ["show_id","title"]].sort_values("title")
# -> rev√≠salo: puede haber mismos t√≠tulos con distinta obra/pa√≠s/a√±o

print("# 3) Estandarizar 'type'")
map_type = {"tv show": "TV Show", "movie": "Movie"}
df["type"] = df["type"].str.strip().str.lower().map(map_type).fillna(df["type"])

print("# 4) Parsear fechas y aislar problemas")
df["date_added_dt"] = pd.to_datetime(df["date_added"], errors="coerce")
fechas_malas = df[df["date_added_dt"].isna() & df["date_added"].notna()][["show_id","date_added"]]

print("# 5) Separar duration -> minutos / temporadas")
def parse_duration(x):
    x = str(x).strip().lower()
    if "min" in x:
        try:
            return int(x.split()[0]), np.nan
        except:
            return np.nan, np.nan
    if "season" in x:
        try:
            return np.nan, int(x.split()[0])
        except:
            return np.nan, np.nan
    return np.nan, np.nan

df[["duration_minutes","seasons"]] = df["duration"].apply(lambda x: pd.Series(parse_duration(x)))

print("# 6) Validar release_year en rango razonable")
MIN_Y, MAX_Y = 1900, 2025
fuera_rango = df[(df["release_year"] < MIN_Y) | (df["release_year"] > MAX_Y)]
# Si quieres corregir:
df.loc[(df["release_year"] < MIN_Y) | (df["release_year"] > MAX_Y), "release_year"] = np.nan

print("# 7) Explode opcional para an√°lisis por pa√≠s / g√©nero")
def split_clean(s):
    return [t.strip() for t in str(s).split(",") if t.strip()]

df_countries = df.dropna(subset=["country"]).assign(country_list=df["country"].apply(split_clean)).explode("country_list")
df_genres    = df.assign(listed_list=df["listed_in"].apply(split_clean)).explode("listed_list")

# 1) Normalizar strings b√°sicos
# Opcional: una copia 'normalizada' para detectar duplicados l√≥gicos
# 2) Detectar t√≠tulos duplicados 'l√≥gicos'
# 3) Estandarizar 'type'
# 4) Parsear fechas y aislar problemas
# 5) Separar duration -> minutos / temporadas
# 6) Validar release_year en rango razonable
# 7) Explode opcional para an√°lisis por pa√≠s / g√©nero

In [13]:

import numpy as np

pd.set_option("display.max_colwidth", 140)
pd.set_option("display.width", 140)

# ---- Utilidades ----
def norm_txt(s: pd.Series):
    return (s.astype(str)
              .str.normalize("NFKD")
              .str.encode("ascii","ignore").str.decode("utf-8")
              .str.strip().str.lower())

def split_clean(s):
    return [t.strip() for t in str(s).split(",") if t and t.strip()]

# Campos texto √∫tiles
text_cols = ["type","title","director","cast","country","rating","duration","listed_in","description","date_added"]
for c in text_cols:
    if c in df.columns:
        df[c] = df[c].astype(str).str.strip()

# Normalizados para detectar duplicados l√≥gicos / casing
dfn = df.copy()
for c in ["type","title","country","rating"]:
    if c in dfn.columns:
        dfn[c + "_norm"] = norm_txt(dfn[c])

# Parseos auxiliares
dfn["date_added_dt"] = pd.to_datetime(dfn["date_added"], errors="coerce", dayfirst=False)

def parse_duration(x):
    x = str(x).strip().lower()
    if "min" in x:
        try: return int(x.split()[0]), np.nan
        except: return np.nan, np.nan
    if "season" in x:
        try: return np.nan, int(x.split()[0])
        except: return np.nan, np.nan
    return np.nan, np.nan

if "duration" in dfn.columns:
    dfn[["duration_minutes","seasons"]] = dfn["duration"].apply(lambda x: pd.Series(parse_duration(x)))

# ==========================================================
# 1) T√çTULOS DUPLICADOS ‚ÄúL√ìGICOS‚Äù
#    (mismo title normalizado; inspecciona si son obras distintas o duplicados reales)
# ==========================================================
dupes_mask = dfn.duplicated(subset=["title_norm"], keep=False)
dupes_title = (dfn.loc[dupes_mask, ["show_id","title","title_norm","release_year","country","type","rating"]]
                   .sort_values(["title_norm","release_year","country"]))
print("\n>>> MUESTRA de t√≠tulos duplicados l√≥gicos (primeros 20):")
print(dupes_title.head(20))

# Resumen por t√≠tulo normalizado
print("\n>>> Top t√≠tulos (normalizados) con m√°s repeticiones:")
print(dupes_title["title_norm"].value_counts().head(10))

# ==========================================================
# 2) FECHAS NO PARSEABLES
# ==========================================================
bad_dates = dfn[dfn["date_added"].notna() & dfn["date_added_dt"].isna()][["show_id","date_added","title","type","release_year"]]
print("\n>>> FECHAS NO PARSEABLES (muestra):")
print(bad_dates.head(15))

print("\n>>> Formatos de fecha problem√°ticos (value_counts):")
print(bad_dates["date_added"].value_counts().head(20))

# ==========================================================
# 3) A√ëOS FUERA DE RANGO (outliers)
# ==========================================================
MIN_Y, MAX_Y = 1900, 2025
yr_out = dfn[(dfn["release_year"] < MIN_Y) | (dfn["release_year"] > MAX_Y)][["show_id","title","release_year","type","country"]]
print("\n>>> A√ëOS fuera de rango (muestra):")
print(yr_out.head(20))
print("\nRango observado:", int(dfn["release_year"].min()), "‚Üí", int(dfn["release_year"].max()))

# ==========================================================
# 4) DURATIONS RARAS (ni minutos ni seasons) o ambiguas
# ==========================================================
if "duration_minutes" in dfn and "seasons" in dfn:
    dur_bad = dfn[dfn["duration"].notna() & dfn["duration_minutes"].isna() & dfn["seasons"].isna()][["show_id","title","duration","type"]]
    print("\n>>> DURATIONS no reconocidas (muestra):")
    print(dur_bad.head(20))

    dur_both = dfn[dfn["duration_minutes"].notna() & dfn["seasons"].notna()][["show_id","title","duration","duration_minutes","seasons","type"]]
    print("\n>>> DURATIONS ambiguas (minutos y seasons simult√°neamente) (muestra):")
    print(dur_both.head(10))

# ==========================================================
# 5) DIRECTORES NULOS (muestra al azar para revisar si conviene imputar)
# ==========================================================
if "director" in dfn.columns:
    dir_null = dfn[dfn["director"].isna() | (dfn["director"].astype(str).str.lower().isin(["nan","none","unknown"]))]
    print("\n>>> DIRECTOR nulo/unknown (muestra):")
    print(dir_null[["show_id","title","type","country","release_year","director"]].sample(min(10, len(dir_null)), random_state=42))

# ==========================================================
# 6) CASING INCONSISTENTE en TYPE / COUNTRY / RATING
#    (compara original vs normalizado para ver si hay variaciones)
# ==========================================================
def show_inconsist(c):
    raw = dfn[c].value_counts().head(10)
    norm = dfn[c + "_norm"].value_counts().head(10)
    print(f"\n>>> Muestras {c} (raw):\n{raw}")
    print(f"\n>>> Muestras {c}_norm:\n{norm}")

for c in ["type","country","rating"]:
    if c + "_norm" in dfn.columns:
        show_inconsist(c)

# ==========================================================
# 7) CAMPOS MULTIVALOR (country / listed_in) ‚Äì inspecci√≥n r√°pida
# ==========================================================
if "country" in dfn.columns:
    countries_exploded = (dfn.dropna(subset=["country"])
                             .assign(country_list=dfn["country"].apply(split_clean))
                             .explode("country_list"))
    print("\n>>> Top pa√≠ses (tras split):")
    print(norm_txt(countries_exploded["country_list"]).value_counts().head(15))

if "listed_in" in dfn.columns:
    genres_exploded = dfn.assign(listed_list=dfn["listed_in"].apply(split_clean)).explode("listed_list")
    print("\n>>> Top g√©neros/categor√≠as (tras split):")
    print(norm_txt(genres_exploded["listed_list"]).value_counts().head(15))

# ==========================================================
# 8) EXPORTAR A EXCEL (para revisi√≥n manual c√≥moda)
#    Crea 'revision_datos.xlsx' con varias hojas: duplicados, fechas malas, a√±os fuera, durations raras, etc.
# ==========================================================
with pd.ExcelWriter("revision_datos.xlsx", engine="xlsxwriter") as xw:
    dupes_title.to_excel(xw, sheet_name="duplicados_titulo", index=False)
    bad_dates.to_excel(xw, sheet_name="fechas_malas", index=False)
    yr_out.to_excel(xw, sheet_name="release_year_outliers", index=False)
    if "duration" in dfn.columns:
        dur_bad.to_excel(xw, sheet_name="duration_no_parse", index=False)
        dur_both.to_excel(xw, sheet_name="duration_ambigua", index=False)
    if "director" in dfn.columns:
        dir_null[["show_id","title","type","country","release_year","director"]].to_excel(xw, sheet_name="director_nulo", index=False)

print("\nArchivo generado: revision_datos.xlsx  (abre y revisa hoja por hoja)")

>>> MUESTRA de t√≠tulos duplicados l√≥gicos (primeros 20):
     show_id                 title            title_norm  release_year                        country     type rating
2638   s2639             ÿßŸÑŸÅ ŸÖÿ®ÿ±ŸàŸÉ                              2009.0                          Egypt    Movie  TV-14
6177   s6178              ÂøçËÄÖ„Éè„ÉÉ„Éà„É™„Åè„Çì                              2012.0                          Japan  TV Show  TV-Y7
7101   s7102                  ÎßàÎÖÄÏÇ¨ÎÉ•                              2015.0                    South Korea  TV Show  TV-MA
8794   s8795                ÿßÿ¥ÿ™ÿ®ÿßŸÉ                              2016.0                  Egypt, France    Movie  TV-14
4914   s4915                  Êµ∑ÁöÑÂÑøÂ≠ê                              2016.0                            nan  TV Show  TV-14
5974   s5975   ‡πÅ‡∏ú‡∏ô‡∏£‡πâ‡∏≤‡∏¢‡∏ô‡∏≤‡∏¢‡πÄ‡∏à‡πâ‡∏≤‡πÄ‡∏•‡πà‡∏´‡πå                              2016.0                            nan  TV Show  TV-14
5022   s5023               Î∞òÎìúÏãú Ïû°ÎäîÎã§                              2017.0                    South Korea    Movie  TV-MA
8774   s8775             ŸäŸàŸÖ ÿßŸÑÿØŸäŸÜ                              2018.0  Egypt, Austria, United States    Movie  TV-14
2639   s2640          ÿØŸÅÿπÿ© ÿßŸÑŸÇÿßŸáÿ±ÿ©                              2019.0                            nan  TV Show  TV-14
5474   s5475                  Ar√®s                  ares        2016.0                         France    Movie  TV-MA
3010   s3011                  Ares                  ares        2020.0                    Netherlands  TV Show  TV-MA
3371   s3372          Consequences          consequences        2014.0                         Turkey    Movie  TV-MA
6529   s6530          Consequences          consequences        2014.0                         Turkey    Movie  TV-MA
5751   s5752            DEATH NOTE            death note        2006.0                          Japan  TV Show  TV-14
5318   s5319            Death Note            death note        2017.0                  United States    Movie  TV-MA
303     s304  Esperando la carroza  esperando la carroza        1985.0                      Argentina    Movie  TV-MA
6705   s6706  Esperando La Carroza  esperando la carroza        1985.0                      Argentina    Movie     NR
5095   s5096   Fullmetal Alchemist   fullmetal alchemist        2003.0                          Japan  TV Show  TV-14
5033   s5034   FullMetal Alchemist   fullmetal alchemist        2017.0                          Japan    Movie  TV-PG
159     s160        Love in a Puff        love in a puff        2010.0                      Hong Kong    Movie  TV-MA

>>> Top t√≠tulos (normalizados) con m√°s repeticiones:
title_norm
                            9
ares                        2
consequences                2
death note                  2
esperando la carroza        2
fullmetal alchemist         2
love in a puff              2
sin senos si hay paraiso    2
veronica                    2
Name: count, dtype: int64

>>> FECHAS NO PARSEABLES (muestra):
     show_id date_added                                        title     type  release_year
6066   s6067        nan  A Young Doctor's Notebook and Other Stories  TV Show        2013.0
6174   s6175        nan              Anthony Bourdain: Parts Unknown  TV Show        2018.0
6795   s6796        nan                                      Frasier  TV Show        2003.0
6806   s6807        nan                                      Friends  TV Show        2003.0
6901   s6902        nan                              Gunslinger Girl  TV Show        2008.0
7196   s7197        nan                                     Kikoriki  TV Show        2010.0
7254   s7255        nan                          La Familia P. Luche  TV Show        2012.0
7406   s7407        nan                                        Maron  TV Show        2016.0
7847   s7848        nan                                 Red vs. Blue  TV Show        2015.0
8182   s8183        nan                 The Adventures of Figaro Pho  TV Show        2015.0

>>> Formatos de fecha problem√°ticos (value_counts):
date_added
nan    10
Name: count, dtype: int64

>>> A√ëOS fuera de rango (muestra):
Empty DataFrame
Columns: [show_id, title, release_year, type, country]
Index: []

Rango observado: 1925 ‚Üí 2021

>>> DURATIONS no reconocidas (muestra):
     show_id                                 title duration   type
5541   s5542                       Louis C.K. 2017      nan  Movie
5794   s5795                 Louis C.K.: Hilarious      nan  Movie
5813   s5814  Louis C.K.: Live at the Comedy Store      nan  Movie

>>> DURATIONS ambiguas (minutos y seasons simult√°neamente) (muestra):
Empty DataFrame
Columns: [show_id, title, duration, duration_minutes, seasons, type]
Index: []

>>> DIRECTOR nulo/unknown (muestra):
     show_id                                                           title     type                                country  \
3295   s3296                                              Green Eggs and Ham  TV Show  United Kingdom, Canada, United States
3367   s3368                                                  Wait, My Youth  TV Show                                  China
1860   s1861                                   The Cabin with Bert Kreischer  TV Show                          United States
2122   s2123                                                        Stranger  TV Show                            South Korea
1300   s1301                                    Amend: The Fight for America  TV Show                          United States
3414   s3415                                                          Chosen  TV Show                                  China
3597   s3598                                                      Knightfall  TV Show                          United States
2869   s2870                                  Amit Tandon: Family Tandoncies    Movie                                  India
89       s90                                                     Mighty Raju  TV Show                                    nan
400     s401  Revelations: The Masters of the Universe: Revelation Aftershow  TV Show                                    nan

      release_year director
3295        2019.0      nan
3367        2019.0      nan
1860        2020.0      nan
2122        2020.0      nan
1300        2021.0      nan
3414        2019.0      nan
3597        2019.0      nan
2869        2019.0      nan
89          2017.0      nan
400         2021.0      nan

>>> Muestras type (raw):
type
Movie      6131
TV Show    2676
Name: count, dtype: int64

>>> Muestras type_norm:
type_norm
movie      6131
tv show    2676
Name: count, dtype: int64

>>> Muestras country (raw):
country
United States     2818
India              972
nan                831
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Name: count, dtype: int64

>>> Muestras country_norm:
country_norm
united states     2818
india              972
nan                831
united kingdom     419
japan              245
south korea        199
canada             181
spain              145
france             124
mexico             110
Name: count, dtype: int64

>>> Muestras rating (raw):
rating
TV-MA    3207
TV-14    2160
TV-PG     863
R         799
PG-13     490
TV-Y7     334
TV-Y      307
PG        287
TV-G      220
NR         80
Name: count, dtype: int64

>>> Muestras rating_norm:
rating_norm
tv-ma    3207
tv-14    2160
tv-pg     863
r         799
pg-13     490
tv-y7     334
tv-y      307
pg        287
tv-g      220
nr         80
Name: count, dtype: int64

>>> Top pa√≠ses (tras split):
country_list
united states     3690
india             1046
nan                831
united kingdom     806
canada             445
france             393
japan              318
spain              232
south korea        231
germany            226
mexico             169
china              162
australia          160
egypt              117
turkey             113
Name: count, dtype: int64

>>> Top g√©neros/categor√≠as (tras split):
listed_list
international movies        2752
dramas                      2427
comedies                    1674
international tv shows      1351
documentaries                869
action & adventure           859
tv dramas                    763
independent movies           756
children & family movies     641
romantic movies              616
tv comedies                  581
thrillers                    577
crime tv shows               470
kids' tv                     451
docuseries                   395
Name: count, dtype: int64

ModuleNotFoundError: No module named 'xlsxwriter'

In [7]:
# fechas malas detectadas
print(fechas_malas.head(10))

# release_year fuera de rango antes de corregir (si guardaste 'fuera_rango')
print(fuera_rango.head(10))

     show_id date_added
6066   s6067        nan
6174   s6175        nan
6795   s6796        nan
6806   s6807        nan
6901   s6902        nan
7196   s7197        nan
7254   s7255        nan
7406   s7407        nan
7847   s7848        nan
8182   s8183        nan
Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, date_added_dt, duration_minutes, seasons]
Index: []

In [8]:
df.to_csv("datos_limpios.csv", index=False, encoding="utf-8-sig")